lz4jsoncat.c: define htole32() on Mac OS X
* Addresses the following error message:

```
lz4jsoncat.c:31:10: fatal error: 'endian.h' file not found
         ^
1 error generated.
make: *** [lz4jsoncat] Error 1
```

* Solution hinted at https://gist.github.com/yinyin/2027912.

* Note that the <endian.h> file is present on OS X as <machine/endian.h>,
  but including it is fruitless, as it doesn't define htole32():

```
lz4jsoncat.c:62:18: warning: implicit declaration of function 'htole32' is invalid in C99 [-Wimplicit-function-declaration]
                size_t outsz = htole32(*(uint32_t *) (map + 8));
                               ^
1 warning generated.
Undefined symbols for architecture x86_64:
  "_htole32", referenced from:
      _main in lz4jsoncat-8ea51e.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [lz4jsoncat] Error 1
```